name: action_repeater
description: Repeats an action after defined timeout period.
environment:
  sdk: ^2.0.0-alpha.86
dependencies:
  action_repeater:
    url: github.com/kaxori/ActionRepeater
    version: ^1.0.0
